export default [
    {
        nombre:'Lionel ' ,
        apellido:'Messi' ,
        edad: 35,
        club: 'PSG (france)' ,
        posicion: 'MCO',
        altura: '1,75' ,
        pieHabil: 'Izquierdo' ,
        titulos: 14 ,
        titulosSeleccion:2 ,
        apodo: 'Pulga',
        goles: 60,
        asistencias: 90,
        amarillas: 4,
        roja:2, 
        fecha:'28 de Junio de 1987',
        img:'https://i.pinimg.com/originals/b3/ce/eb/b3ceebb4d10bf4d238ebceeda192fc42.jpg',
        golesClun : 700 ,
        golesSeleccion : 60
    },
    {
        nombre:'Rodrigo' ,
        apellido: 'De Paul' ,
        edad: 28 ,
        club: 'Atletico de Madrid',
        posicion: 'MC' ,
        altura: '1,78' ,
        pieHabil: 'Derecho' ,
        titulos: 2 ,
        titulosSeleccion:1 ,
        apodo: 'Diosito',
        goles: 6,
        asistencias:10,
        amarillas:2,
        roja:0, 
        fecha:'24 de mayo de 1994',
        img: 'https://images.ole.com.ar/2021/11/16/yKKpjQujC_2000x1500__1.jpg',
        golesClun : 700 ,
        golesSeleccion : 5
    },
    {
        nombre:'Angel' ,
        apellido: 'Di Maria' ,
        edad: 36 ,
        club: 'Juventus' ,
        posicion: 'MCO' ,
        altura: '1,79' ,
        pieHabil: 'Izquierdo' ,
        titulos: 10 ,
        titulosSeleccion: 2,
        apodo:'Fideo',
        goles: 20,
        asistencias:10,
        amarillas:4,
        roja:0, 
        fecha:'14 de febrero de 1988',
        img: 'https://i.pinimg.com/736x/e6/fc/99/e6fc992f30d9560858989b4449ceb5f4.jpg',
        golesClun : 700 ,
        golesSeleccion : 20 
    },
    {
        nombre:'Lautaro' ,
        apellido:'Matinez' ,
        edad: 25 ,
        club: 'Inter de milan' ,
        posicion: 'DC',
        altura: '1,80',
        pieHabil: 'Drecho',
        titulos: 4 ,
        titulosSeleccion:1 ,
        apodo: 'Toro' ,goles:20,
        asistencias:10,
        amarillas:4,
        roja:0, 
        fecha:'22 de agosto de 1997',
        img: 'https://media.tycsports.com/files/2021/06/15/294628/lautaro-martinez_862x485_wmk.jpg?v=1',
        golesClun : 700 ,
        golesSeleccion : 30 
    },
    {
        nombre:'Nicolas' ,
        apellido: 'Otamendi' ,
        edad: 33 ,
        club: 'Sevilla FC' ,
        posicion: 'DFC',
        altura:'1,80' ,
        pieHabil: 'Derecho',
        titulos: 3 ,
        titulosSeleccion:1 ,
        apodo:'Tanque',
        goles:0,
        asistencias:0,
        amarillas:6,
        roja:3, 
        fecha:' 12 de febrero de 1988',
        img: 'https://media.minutouno.com/p/010dd316f50e88d2075b651dd70043ed/adjuntos/150/imagenes/039/963/0039963321/nicolas-otamendijpg.jpg',
        golesClun : 700 ,
        golesSeleccion : 0  
    },
    {
        nombre: 'julian' ,
        apellido: 'Alvarez' ,
        edad: 22 ,
        club:'Manchester City' ,
        posicion: 'DC' ,
        altura: '1,80' ,
        pieHabil: 'Derecho',
        titulos:5 ,
        titulosSeleccion:2,
        apodo:'Araña',
        goles:14,
        asistencias:10,
        amarillas:2,
        roja:0, 
        fecha:' 31 de enero de 2000',
        img: 'https://i.pinimg.com/736x/f5/74/89/f57489ae01280c34e0b10ea1308350a1.jpg'  ,
        golesClun : 700 ,
        golesSeleccion : 25
    },
    {
        nombre:'Leandro' ,
        apellido: 'Paredes',
        edad: 29 ,
        club: 'Juventus' ,
        posicion: 'MC' ,
        altura: '1,80',
        pieHabil: 'Derecho' ,
        titulos: 3 ,
        titulosSeleccion:1 ,
        apodo:'Leo' ,
        goles:5,
        asistencias:10,
        amarillas:4,
        roja:2, 
        fecha:'29 de junio de 1994',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvWYSgJ1zqBVs4l2a0w_LLe7JavbMHhc-e4Q&usqp=CAU.jpg',
        golesClun : 700 ,
        golesSeleccion : 6
        
    },
    {
        nombre:'Alejandro' ,
        apellido: 'Gomez',
        edad: 34 ,
        club: 'Sevill FC' ,
        posicion: 'MC' ,
        altura: '1,67',
        pieHabil: 'Derecho' ,
        titulos: 3 ,
        titulosSeleccion:1 ,
        apodo:'Papu' ,
        goles:5,
        asistencias:10,
        amarillas:4,
        roja:0, 
        fecha:'15 de febrero de 1988 ',
        img: 'https://e00-ar-marca.uecdn.es/claro/assets/multimedia/imagenes/2020/07/12/15945243824757.jpg',
        golesClun : 700 ,
        golesSeleccion : 6
        
    },
    {
        nombre:'Emiliano' ,
        apellido: 'Martinez',
        edad: 30 ,
        club: 'Aston Villa' ,
        posicion: 'PO' ,
        altura: '1,95',
        pieHabil: 'Derecho' ,
        titulos: 2 ,
        titulosSeleccion:1 ,
        apodo:'Dibu' ,
        goles:5,
        asistencias:0,
        amarillas:0,
        roja:0, 
        fecha:' 2 de septiembre de 1992 ',
        img: 'https://cloudfront-us-east-1.images.arcpublishing.com/infobae/GS72ZCZ4D73SZD4I6HMCOY46PQ.jpg',
        golesClun : 700 ,
        golesSeleccion : 6
        
    },
    {
        nombre:'Cristian' ,
        apellido: 'Romero',
        edad: 24 ,
        club: 'Tottenham' ,
        posicion: 'PO' ,
        altura: '1,85',
        pieHabil: 'Derecho' ,
        titulos: 2 ,
        titulosSeleccion:1 ,
        apodo:'Cuti' ,
        goles:0,
        asistencias:0,
        amarillas:0,
        roja:0, 
        fecha:'  27 de abril de 1998  ',
        img: 'https://mundoalbiceleste.com/wp-content/uploads/2021/06/argentina.jpg',
        golesClun : 700 ,
        golesSeleccion : 6
        
    }

]